import type { Question } from '../models/question';
import { generateId } from '../utils/id';

const SEED_QUESTIONS: Omit<Question, 'id' | 'createdAt' | 'updatedAt' | 'stats'>[] = [
  // A. 技术架构与方案设计
  {
    title: '请介绍你过往最有代表性的一个项目，从架构设计角度展开',
    content: '考察点：方案全局视野、技术选型逻辑、业务理解深度\n建议框架：业务背景 -> 技术挑战 -> 架构方案 -> 落地成果 -> 复盘反思',
    category: 'architecture',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '通用' }],
    difficulty: 'medium',
    source: 'SA面经常规题',
  },
  {
    title: '如何为一个医疗系统设计高可用架构？',
    content: '重点考虑：7x24不间断服务、多院区容灾、数据一致性、紧急降级方案。医疗系统对可用性的要求极高，需要考虑到各种异常场景。',
    category: 'architecture',
    tags: [{ key: 'position', value: 'SA' }, { key: 'industry', value: '医疗' }, { key: 'company', value: '通用' }, { key: 'skill', value: '高可用' }],
    difficulty: 'hard',
    referenceAnswer: '1. 多活架构设计，主备切换机制\n2. 数据库主从复制+读写分离\n3. 服务降级策略（非核心服务优先降级）\n4. 监控告警体系\n5. 灾难恢复演练',
    source: '阿里SA面经-医疗方向',
  },
  {
    title: '设计一个支持10万人同时在线的在线教育直播平台架构',
    content: '考察音视频架构（WebRTC/RTMP）、CDN分发策略、消息队列削峰、数据库分库分表、弹性扩容策略。\n延伸：如何保障弱网环境下的用户体验？如何做课堂互动（弹幕、连麦、白板）？',
    category: 'architecture',
    tags: [{ key: 'position', value: 'SA' }, { key: 'industry', value: '教育' }, { key: 'company', value: '通用' }, { key: 'skill', value: '高可用' }],
    difficulty: 'hard',
    referenceAnswer: '1. 音视频层：RTMP推流+CDN分发+WebRTC连麦\n2. 接入层：负载均衡+Nginx集群\n3. 业务层：微服务拆分（用户、课程、直播、互动）\n4. 数据层：Redis缓存+MySQL分库+MongoDB存储弹幕\n5. 弹性：K8s自动扩缩容+预置资源池',
    source: '阿里SA面经-教育方向',
  },
  {
    title: '设计一个互联网医院的整体解决方案架构',
    content: '涵盖在线问诊（IM+音视频）、电子处方流转、医保对接、HIS/EMR系统打通、多端适配。\n延伸：数据隔离与隐私保护方案、医疗数据合规（等保三级、患者知情同意）',
    category: 'architecture',
    tags: [{ key: 'position', value: 'SA' }, { key: 'industry', value: '医疗' }, { key: 'company', value: '阿里云' }, { key: 'skill', value: 'AI' }],
    difficulty: 'hard',
    source: '阿里SA面经-医疗方向',
  },
  {
    title: '谈谈你对微服务架构在行业落地中的理解，优势和挑战分别是什么？',
    content: '不是纯理论，要结合行业场景。比如医疗系统中，模块切分宜粗不宜细；教育系统中，直播服务和题库服务可以独立拆分。\n参考观点："不大的系统单服务才是王者"，避免过度设计。',
    category: 'architecture',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '通用' }, { key: 'skill', value: '微服务' }],
    difficulty: 'medium',
    source: '阿里SA面经常规题',
  },
  {
    title: '如何选择技术栈？请结合一个具体场景说明你的决策过程',
    content: '考察技术选型的权衡能力，不能只谈"最好"的技术，要谈"最合适"的技术。\n建议从成本、团队能力、业务阶段、运维复杂度多维度展开。',
    category: 'architecture',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '通用' }],
    difficulty: 'medium',
    source: '阿里SA面经常规题',
  },

  // B. 行业理解与业务洞察
  {
    title: '你如何理解医疗行业的数字化转型痛点？',
    content: '关键痛点：数据孤岛严重、系统老旧（很多还在用Oracle/SQL Server单机）、合规要求高、业务流程复杂、个性化需求多。',
    category: 'industry',
    tags: [{ key: 'position', value: 'SA' }, { key: 'industry', value: '医疗' }, { key: 'company', value: '通用' }],
    difficulty: 'medium',
    source: '阿里SA面经-医疗方向',
  },
  {
    title: '教育行业数字化转型的核心挑战是什么？',
    content: '关键挑战：线上线下融合难、学情数据分散、直播技术门槛高、教育公平性问题、OMO转型挑战。',
    category: 'industry',
    tags: [{ key: 'position', value: 'SA' }, { key: 'industry', value: '教育' }, { key: 'company', value: '通用' }],
    difficulty: 'medium',
    source: '阿里SA面经-教育方向',
  },
  {
    title: '阿里云在医疗行业有哪些核心产品和解决方案？你如何向客户推荐？',
    content: '方向：医疗健康全场景解决方案、互联网医院安全解决方案、医疗大数据平台。\n考察对阿里云产品矩阵的熟悉度和售前方案包装能力。',
    category: 'industry',
    tags: [{ key: 'position', value: 'SA' }, { key: 'industry', value: '医疗' }, { key: 'company', value: '阿里云' }],
    difficulty: 'hard',
    source: '阿里SA面经-医疗方向',
  },
  {
    title: '阿里云在教育行业有哪些解决方案？',
    content: '方向：在线教育解决方案、智慧教育局校平台、AI教育大模型。\n需要了解教育行业的技术趋势和阿里云的竞争优势。',
    category: 'industry',
    tags: [{ key: 'position', value: 'SA' }, { key: 'industry', value: '教育' }, { key: 'company', value: '阿里云' }],
    difficulty: 'medium',
    source: '阿里SA面经-教育方向',
  },
  {
    title: '如何评估一个客户是适合用公有云、私有云还是混合云？',
    content: '考察点：成本分析、安全合规、运维能力、业务弹性需求。\n医疗场景：通常倾向混合云（核心数据私有化+互联网服务公有云）\n教育场景：通常倾向公有云（弹性需求大+成本敏感）',
    category: 'industry',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '通用' }, { key: 'skill', value: '云计算' }],
    difficulty: 'medium',
    source: '阿里SA面经常规题',
  },
  {
    title: '如何帮助传统医院/学校做上云迁移规划？',
    content: '考察迁移方法论：评估 -> 规划 -> 迁移 -> 优化。需要了解风险评估、分阶段实施策略。',
    category: 'industry',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '通用' }, { key: 'skill', value: '云计算' }],
    difficulty: 'medium',
    source: '阿里SA面经常规题',
  },

  // C. 安全合规与成本优化
  {
    title: '医疗数据的安全合规有哪些要求？如何在架构层面保障？',
    content: '重点：等保三级、数据脱敏、传输加密（TLS）、访问控制（RBAC）、审计日志、数据备份与容灾。\n延伸：跨境数据传输（如涉及跨国药企）的合规方案。',
    category: 'security',
    tags: [{ key: 'position', value: 'SA' }, { key: 'industry', value: '医疗' }, { key: 'company', value: '通用' }, { key: 'skill', value: '安全' }],
    difficulty: 'hard',
    source: '阿里SA面经-医疗方向',
  },
  {
    title: '如何在保障系统性能的前提下控制云计算成本？',
    content: '考察点：资源利用率优化、弹性伸缩策略、Spot实例/预留实例选择、存储分级、监控与告警。\n建议举出实际优化案例，如通过架构调整将月成本降低30%。',
    category: 'security',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '通用' }, { key: 'skill', value: '云计算' }],
    difficulty: 'medium',
    source: '阿里SA面经常规题',
  },

  // D. POC与售前能力
  {
    title: '描述一次你主导的POC（概念验证）项目的全过程',
    content: '考察：需求调研 -> 方案设计 -> 环境搭建 -> 测试验证 -> 结果汇报的全链路能力。\n建议突出如何量化POC成果、如何说服客户决策层。',
    category: 'presales',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '通用' }],
    difficulty: 'medium',
    source: '阿里SA面经常规题',
  },
  {
    title: '如何在15分钟内向CTO/CIO介绍一个技术方案？',
    content: '考察结构化表达、提炼核心价值、避免技术细节堆砌。\n框架建议：痛点 -> 方案 -> 差异化优势 -> ROI -> 下一步',
    category: 'presales',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '通用' }],
    difficulty: 'medium',
    source: '阿里SA面经常规题',
  },
  {
    title: '客户对阿里云方案提出质疑（如价格高于竞品），你如何应对？',
    content: '考察售前应变能力、价值导向沟通、竞品对比分析。\n参考：强调生态完善度、技术支持响应、长期TCO优势。',
    category: 'presales',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '阿里云' }],
    difficulty: 'medium',
    source: '阿里SA面经常规题',
  },

  // E. 团队协作与项目管理
  {
    title: '如何协调销售团队、产品团队和技术团队之间的需求冲突？',
    content: '考察跨部门沟通能力、冲突管理、优先级决策。',
    category: 'teamwork',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '通用' }],
    difficulty: 'medium',
    source: '阿里SA面经常规题',
  },
  {
    title: '面对紧迫的项目交付期限，你如何安排资源和优先级？',
    content: '考察项目管理方法论、风险评估、敏捷实践能力。',
    category: 'teamwork',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '通用' }],
    difficulty: 'medium',
    source: '阿里SA面经常规题',
  },

  // F. HR面问题
  {
    title: '为什么选择阿里云SA这个岗位？',
    content: '考察求职动机、对岗位的理解、职业规划。',
    category: 'hr',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '阿里云' }],
    difficulty: 'easy',
    source: '阿里SA面经-HR面',
  },
  {
    title: '你对医疗/教育行业未来3年的发展趋势怎么看？',
    content: '考察行业洞察力和前瞻性思维。',
    category: 'hr',
    tags: [{ key: 'position', value: 'SA' }, { key: 'industry', value: '医疗' }, { key: 'company', value: '通用' }],
    difficulty: 'medium',
    source: '阿里SA面经-HR面',
  },
  {
    title: '你最有成就感的一个项目是什么？',
    content: '考察项目管理能力、技术深度、价值导向。建议用STAR法则回答。',
    category: 'hr',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '通用' }],
    difficulty: 'easy',
    source: '阿里SA面经-HR面',
  },
  {
    title: '你的职业规划是什么？',
    content: '考察长期规划能力和稳定性。',
    category: 'hr',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '通用' }],
    difficulty: 'easy',
    source: '阿里SA面经-HR面',
  },
  {
    title: '对薪资的期望是多少？',
    content: 'HR常见问题，需要了解市场行情。',
    category: 'hr',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '通用' }],
    difficulty: 'easy',
    source: '阿里SA面经-HR面',
  },

  // =========================================
  // G. 架构设计 - 新增刷题题库 (9题)
  // =========================================
  {
    title: '请设计一个支持千万级用户并发的电商秒杀系统架构',
    content: '考察分布式系统设计的综合能力。重点关注：高并发接入层设计、库存扣减的数据一致性、防超卖方案、限流降级策略、缓存预热与穿透防护。\n延伸：如何做到秒杀开始前不压垮后端？如何处理恶意刷单？',
    category: 'architecture',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '通用' }, { key: 'skill', value: '分布式' }, { key: 'skill', value: '高可用' }],
    difficulty: 'hard',
    referenceAnswer: '1. 接入层：CDN静态化+多级缓存+令牌桶限流\n2. 服务层：独立秒杀服务+异步队列(RocketMQ)削峰\n3. 数据层：Redis预扣库存+数据库乐观锁最终一致\n4. 防刷：用户维度限购+IP频控+验证码\n5. 降级：非核心服务熔断+兜底方案',
    source: '网络整理',
  },
  {
    title: '如何设计一个支持百万并发的消息推送系统？',
    content: '考察高并发、长连接管理、消息队列、水平扩展等要点。需考虑WebSocket连接管理、消息可靠投递、消息顺序保证、离线消息存储。\n延伸：如何做连接状态的分布式管理？如何处理消息风暴？',
    category: 'architecture',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '通用' }, { key: 'skill', value: '分布式' }, { key: 'skill', value: '高可用' }],
    difficulty: 'hard',
    referenceAnswer: '1. 连接层：Netty/Gateway管理百万长连接，按UID哈希分片\n2. 路由层：Redis维护UID→连接节点映射\n3. 消息层：Kafka/RocketMQ解耦生产与消费\n4. 存储层：HBase/Cassandra存离线消息，Redis做已读标记\n5. 扩展性：无状态服务节点水平扩容',
    source: '网络整理',
  },
  {
    title: '在一个多服务依赖的分布式系统中，某核心服务突然响应缓慢，你如何快速定位问题？',
    content: '考察分布式系统故障排查能力。需要展示系统化的排查思路：从监控告警到链路追踪、从日志分析到资源瓶颈定位。\n延伸：你使用过哪些APM工具？如何设计一个完善的可观测性体系？',
    category: 'architecture',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '通用' }, { key: 'skill', value: '微服务' }],
    difficulty: 'medium',
    referenceAnswer: '1. 快速止血：限流+熔断+降级非核心功能\n2. 定位问题：链路追踪(Jaeger/SkyWalking)定位慢调用\n3. 资源分析：CPU/内存/网络/磁盘IO/GC日志\n4. 根因排查：数据库慢查询、连接池耗尽、下游超时\n5. 长效机制：全链路压测+混沌工程+SLO告警',
    source: '网络整理',
  },
  {
    title: '如何设计分布式事务方案以保证跨服务的数据一致性？',
    content: '考察分布式事务的理解深度。需比较2PC/3PC/TCC/Saga/本地消息表等方案的优劣势，结合具体业务场景选型。\n延伸：在微服务架构下，你更推荐哪种方案？为什么？',
    category: 'architecture',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '通用' }, { key: 'skill', value: '分布式' }, { key: 'skill', value: '数据库' }],
    difficulty: 'hard',
    referenceAnswer: '1. 强一致：2PC(Seata AT)适合单体拆分的强一致场景\n2. 最终一致：Saga模式适合长事务(订单→支付→发货)\n3. TCC：适合资金类高一致性要求场景\n4. 本地消息表+MQ：最轻量的最终一致方案\n5. 选型建议：优先BASE理论，避免分布式事务滥用',
    source: '网络整理',
  },
  {
    title: '请设计一个多租户SaaS平台的数据隔离方案',
    content: '考察SaaS架构设计能力。需比较独立数据库/共享数据库独立Schema/共享表三种隔离模式的优缺点，考虑数据安全、成本、运维复杂度。\n延伸：如何支持租户自定义配置？如何做租户级别的资源配额和限流？',
    category: 'architecture',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '阿里云' }, { key: 'skill', value: '云计算' }],
    difficulty: 'hard',
    referenceAnswer: '1. 大客户：独立数据库实例(物理隔离)\n2. 中等客户：共享实例独立Schema(逻辑隔离)\n3. 小客户：共享表+tenant_id字段(成本最优)\n4. 租户配置：配置中心+Nacos按租户隔离\n5. 资源配额：按租户限流+配额管理+计费',
    source: '网络整理',
  },
  {
    title: '如何设计一个高可用的API网关？',
    content: '考察网关层架构设计。需涵盖路由转发、负载均衡、限流熔断、鉴权认证、协议转换、灰度发布等核心能力。\n延伸：自研网关和开源方案(Kong/APISIX)如何选型？',
    category: 'architecture',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '通用' }, { key: 'skill', value: '微服务' }, { key: 'skill', value: '高可用' }],
    difficulty: 'medium',
    referenceAnswer: '1. 核心能力：路由+限流+鉴权+日志+协议转换\n2. 高可用：多节点部署+LB+无状态设计\n3. 性能：异步非阻塞(Netty/Envoy)+连接池+缓存\n4. 扩展性：插件化架构+热加载\n5. 选型：小团队用Kong/APISIX，大规模可自研',
    source: '网络整理',
  },
  {
    title: '如何为大型系统设计容量评估和全链路压测方案？',
    content: '考察性能工程能力。需要从业务指标推算技术指标(QPS/TPS/存储/带宽)，设计压测场景和数据准备方案。\n延伸：如何在不影响线上数据的情况下做全链路压测？',
    category: 'architecture',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '通用' }, { key: 'skill', value: '高可用' }],
    difficulty: 'medium',
    referenceAnswer: '1. 容量评估：DAU→QPS(二八原则)→存储→带宽\n2. 压测设计：单接口→场景→全链路→生产压测\n3. 数据隔离：影子库+影子表+流量标记\n4. 工具：JMeter/Gatling+自研流量回放\n5. 常态化：定期压测+性能基线+自动回归',
    source: '网络整理',
  },
  {
    title: '设计一个支持多地域部署的全球加速方案',
    content: '考察全球化架构设计。需涵盖DNS智能解析、CDN加速、数据同步策略、就近接入、异地容灾切换。\n延伸：如何解决跨地域数据一致性与延迟的矛盾？',
    category: 'architecture',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '阿里云' }, { key: 'skill', value: '云计算' }, { key: 'skill', value: '高可用' }],
    difficulty: 'hard',
    referenceAnswer: '1. 接入层：GeoDNS就近接入+CDN静态资源加速\n2. 应用层：多Region部署+GA全球加速(阿里云)\n3. 数据层：主Region写入+跨Region异步复制\n4. 容灾：DNS切换+RTO/RPO策略+定期演练\n5. 一致性：CRDT/最终一致+冲突解决策略',
    source: '网络整理',
  },
  {
    title: '如何设计一个事件驱动的架构(EDA)来解耦复杂业务系统？',
    content: '考察架构设计模式和异步通信的理解。需涵盖事件模型设计、事件溯源(Event Sourcing)、CQRS、事件路由和过滤。\n延伸：如何保证事件的可靠投递和幂等消费？',
    category: 'architecture',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '通用' }, { key: 'skill', value: '微服务' }, { key: 'skill', value: '分布式' }],
    difficulty: 'hard',
    referenceAnswer: '1. 事件建模：领域事件+事件总线(EventBridge)\n2. 可靠投递：At-least-once+消费端幂等\n3. Event Sourcing：事件日志作为数据源真相\n4. CQRS：读写分离提升性能\n5. 治理：事件Schema注册+版本管理+死信队列',
    source: '网络整理',
  },

  // =========================================
  // H. 云计算技术 - 新增刷题题库 (9题)
  // =========================================
  {
    title: '请比较Kubernetes中Deployment、StatefulSet和DaemonSet的适用场景',
    content: '考察K8s工作负载管理的基础功底。需清晰说明三者的区别、Pod管理方式、存储卷绑定策略，以及各自的典型应用场景。\n延伸：如何实现K8s中应用的优雅发布和回滚？',
    category: 'architecture',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '通用' }, { key: 'skill', value: '容器化' }, { key: 'skill', value: 'DevOps' }],
    difficulty: 'medium',
    referenceAnswer: '1. Deployment：无状态应用(Web服务)，支持滚动更新\n2. StatefulSet：有状态应用(数据库)，稳定网络标识+持久存储\n3. DaemonSet：每个节点运行一个Pod(日志收集/监控Agent)\n4. 优雅发布：readinessProbe+preStop hook+滚动策略\n5. 回滚：kubectl rollout undo+版本管理',
    source: '网络整理',
  },
  {
    title: '如何设计一个基于Kubernetes的微服务可观测性体系？',
    content: '考察云原生环境下的运维能力。需涵盖三大支柱：Metrics(Prometheus+Grafana)、Logging(EFK/Loki)、Tracing(Jaeger/SkyWalking)。\n延伸：如何在海量日志中快速定位问题？告警风暴如何处理？',
    category: 'architecture',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '通用' }, { key: 'skill', value: '容器化' }, { key: 'skill', value: 'DevOps' }],
    difficulty: 'medium',
    referenceAnswer: '1. Metrics：Prometheus采集+Grafana展示+AlertManager告警\n2. Logging：Filebeat→Logstash→ES(或Loki轻量方案)\n3. Tracing：OpenTelemetry SDK+Jaeger后端\n4. 关联：TraceID贯穿全链路，日志中注入SpanID\n5. 告警治理：分级告警+告警聚合+静默+抑制',
    source: '网络整理',
  },
  {
    title: 'Serverless架构的适用场景和局限性是什么？请结合实际案例说明',
    content: '考察对Serverless的理解深度，不仅是概念，要有实际落地经验。需涵盖FaaS/BaaS区别、冷启动问题、成本控制、厂商锁定。\n延伸：阿里云函数计算(FC)在什么场景下比ECS更合适？',
    category: 'architecture',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '阿里云' }, { key: 'skill', value: '云计算' }],
    difficulty: 'medium',
    referenceAnswer: '1. 适用：事件驱动(文件处理/Webhook)、低频API、定时任务\n2. 优势：免运维+按需付费+自动弹性\n3. 局限：冷启动延迟(预留实例解决)、执行时长限制、调试困难\n4. 成本：低流量省钱，高流量可能比ECS贵\n5. 案例：图片处理管线、IoT数据接入、BFF层',
    source: '网络整理',
  },
  {
    title: '什么是基础设施即代码(IaC)？如何在企业环境中落地？',
    content: '考察DevOps和自动化运维能力。需比较Terraform/Pulumi/Ansible等工具的适用场景，讨论状态管理、团队协作、安全合规。\n延伸：阿里云ROS和Terraform如何选型？如何管理多环境的IaC？',
    category: 'architecture',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '阿里云' }, { key: 'skill', value: 'DevOps' }, { key: 'skill', value: '云计算' }],
    difficulty: 'medium',
    referenceAnswer: '1. 工具选型：Terraform多云/ROS阿里云原生/Ansible配置管理\n2. 落地步骤：模块化→环境隔离(dev/staging/prod)→CI/CD集成\n3. 状态管理：远程State(S3/OSS)+Locking(DynamoDB)\n4. 安全：Secret管理(Vault)+最小权限IAM+合规检查\n5. 治理：Code Review+Drift Detection+成本预估',
    source: '网络整理',
  },
  {
    title: '如何设计混合云架构以兼顾数据安全和业务弹性？',
    content: '考察混合云方案设计能力。需考虑专线/VPN连接、数据同步策略、统一身份认证、跨云资源调度、灾备方案。\n延伸：医疗/金融行业在混合云场景下的特殊要求是什么？',
    category: 'architecture',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '阿里云' }, { key: 'skill', value: '云计算' }, { key: 'skill', value: '安全' }],
    difficulty: 'hard',
    referenceAnswer: '1. 网络：专线(Express Connect)+VPN双链路冗余\n2. 数据：核心数据私有云+非核心数据公有云+异步同步\n3. 身份：LDAP/AD集成+SSO+统一权限管理\n4. 弹性：公有云作为弹性扩容层(K8s联邦)\n5. 行业：医疗需等保三级+数据不出院；金融需两地三中心',
    source: '网络整理',
  },
  {
    title: 'Kubernetes集群的安全加固有哪些关键措施？',
    content: '考察云原生安全能力。需涵盖网络策略(NetworkPolicy)、RBAC权限控制、镜像安全扫描、Pod安全标准、Secret管理。\n延伸：如何检测和防御K8s环境下的安全攻击（如容器逃逸）？',
    category: 'security',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '通用' }, { key: 'skill', value: '容器化' }, { key: 'skill', value: '安全' }],
    difficulty: 'hard',
    referenceAnswer: '1. 网络：NetworkPolicy隔离+Service Mesh mTLS\n2. 权限：RBAC最小权限+Pod ServiceAccount隔离\n3. 镜像：Trivy扫描+签名验证+私有Registry\n4. Pod安全：Pod Security Standards(Privileged/Baseline/Restricted)\n5. Secret：External Secrets Operator+Vault集成',
    source: '网络整理',
  },
  {
    title: '如何设计基于云原生的CI/CD流水线？',
    content: '考察DevOps工程实践能力。需涵盖代码提交→构建→测试→安全扫描→部署→监控的全流程设计，以及GitOps实践。\n延伸：如何实现蓝绿部署和金丝雀发布？ArgoCD和Flux如何选型？',
    category: 'architecture',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '通用' }, { key: 'skill', value: 'DevOps' }, { key: 'skill', value: '容器化' }],
    difficulty: 'medium',
    referenceAnswer: '1. 流水线：GitLab CI/GitHub Actions+Kaniko构建+Helm部署\n2. 安全门禁：SAST/DAST+镜像扫描+License检查\n3. 发布策略：Argo Rollouts实现金丝雀/蓝绿\n4. GitOps：ArgoCD监听Git仓库自动同步\n5. 环境管理：dev→staging→prod渐进式+审批门禁',
    source: '网络整理',
  },
  {
    title: '容器化改造时如何选择合适的镜像基础和安全最佳实践？',
    content: '考察容器化落地经验。需涵盖基础镜像选择(distroless/alpine)、多阶段构建、镜像瘦身、运行时安全、日志和监控集成。\n延伸：如何处理有状态应用的容器化？',
    category: 'architecture',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '通用' }, { key: 'skill', value: '容器化' }, { key: 'skill', value: '安全' }],
    difficulty: 'medium',
    referenceAnswer: '1. 基础镜像：distroless(最小攻击面)/alpine(轻量调试)\n2. 构建：多阶段构建分离编译和运行环境\n3. 瘦身：清理缓存+合并RUN+使用.dockerignore\n4. 运行时：只读RootFS+非root用户+resource limits\n5. 有状态：PVC+Operator模式(StatefulSet+自定义控制器)',
    source: '网络整理',
  },
  {
    title: '阿里云的弹性伸缩策略如何设计以兼顾成本和性能？',
    content: '考察阿里云产品深度理解。需涵盖ESS伸缩组配置、伸缩规则(定时/动态/预测)、Spot实例策略、预留实例与按量搭配。\n延伸：如何避免弹性伸缩中的"雪崩效应"？',
    category: 'architecture',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '阿里云' }, { key: 'skill', value: '云计算' }],
    difficulty: 'medium',
    referenceAnswer: '1. 伸缩策略：定时伸缩(已知波峰)+动态伸缩(CPU/QPS阈值)\n2. 成本优化：Spot实例做弹性层+预留实例做基线\n3. 冷却时间：避免频繁伸缩+预热新实例\n4. 多AZ分散：提高可用性\n5. 防雪崩：限制最大实例数+慢启动+健康检查',
    source: '网络整理',
  },

  // =========================================
  // I. 行业解决方案 - 新增刷题题库 (9题)
  // =========================================
  {
    title: '如何为一家三甲医院设计智慧医院整体解决方案？',
    content: '考察医疗行业方案设计能力。需涵盖智慧诊疗(AI辅助诊断)、智慧服务(互联网医院)、智慧管理(HRP/绩效)三大板块。\n延伸：如何打通院内HIS/EMR/LIS/PACS等异构系统？',
    category: 'industry',
    tags: [{ key: 'position', value: 'SA' }, { key: 'industry', value: '医疗' }, { key: 'company', value: '阿里云' }, { key: 'skill', value: 'AI' }],
    difficulty: 'hard',
    referenceAnswer: '1. 智慧诊疗：AI辅助影像诊断+CDSS临床决策支持\n2. 智慧服务：互联网医院(在线问诊/处方/配送)\n3. 智慧管理：HRP资源管理+BI运营分析\n4. 集成平台：ESB/API Gateway统一异构系统对接\n5. 数据中台：患者360视图+医疗数据治理',
    source: '网络整理',
  },
  {
    title: '如何为K12教育机构设计OMO(Online-Merge-Offline)教学平台？',
    content: '考察教育行业方案设计能力。需涵盖线上线下融合教学、学情数据分析、自适应学习、家校互动、直播互动课堂。\n延伸：如何利用AI大模型赋能个性化学习？',
    category: 'industry',
    tags: [{ key: 'position', value: 'SA' }, { key: 'industry', value: '教育' }, { key: 'company', value: '阿里云' }, { key: 'skill', value: 'AI' }],
    difficulty: 'hard',
    referenceAnswer: '1. 教学平台：直播课堂+录播回放+互动白板+分组讨论\n2. 学情分析：多维数据采集→知识图谱→薄弱点诊断\n3. 自适应学习：AI推荐学习路径+智能出题\n4. 家校互动：作业推送+学情报告+家长端\n5. AI赋能：大模型作文批改+口语评测+智能答疑',
    source: '网络整理',
  },
  {
    title: '如何为零售企业设计全渠道数字化中台？',
    content: '考察零售行业和中台架构设计能力。需涵盖商品中心、订单中心、会员中心、营销中心、库存中心的拆合逻辑。\n延伸：如何处理线上线下的库存冲突和价格不一致？',
    category: 'industry',
    tags: [{ key: 'position', value: 'SA' }, { key: 'industry', value: '零售' }, { key: 'company', value: '通用' }],
    difficulty: 'hard',
    referenceAnswer: '1. 商品中心：统一SKU+多渠道价格策略\n2. 订单中心：全渠道订单归集+智能拆单合单\n3. 库存中心：实时库存同步+就近发货+预占释放\n4. 会员中心：OneID统一会员+积分通兑\n5. 营销中心：优惠券/满减/拼团等营销工具',
    source: '网络整理',
  },
  {
    title: '金融行业数字化转型的核心挑战和解决方案是什么？',
    content: '考察金融行业理解和方案设计能力。核心挑战：监管合规(银保监/证监会)、数据安全、核心系统去IOE、分布式转型。\n延伸：如何帮助城商行做核心系统分布式改造？',
    category: 'industry',
    tags: [{ key: 'position', value: 'SA' }, { key: 'industry', value: '金融' }, { key: 'company', value: '阿里云' }],
    difficulty: 'hard',
    referenceAnswer: '1. 合规：等保三级+金融云专区+数据分类分级\n2. 核心系统：从IOE迁移到分布式(微服务+分布式数据库)\n3. 两地三中心：同城双活+异地灾备\n4. 风控：实时风控引擎+反欺诈+知识图谱\n5. 开放银行：API开放平台+BaaS模式',
    source: '网络整理',
  },
  {
    title: '如何为政务行业设计一体化政务服务平台？',
    content: '考察政务行业方案设计能力。需涵盖"最多跑一次"、数据共享交换、电子证照、一网通办、跨部门协同。\n延伸：如何打通各委办局的数据孤岛？信创要求下如何选型？',
    category: 'industry',
    tags: [{ key: 'position', value: 'SA' }, { key: 'industry', value: '政务' }, { key: 'company', value: '阿里云' }],
    difficulty: 'hard',
    referenceAnswer: '1. 一网通办：统一门户+统一身份认证+统一支付\n2. 数据共享：政务数据共享交换平台+数据目录\n3. 电子证照：区块链存证+跨部门互认\n4. 信创适配：国产CPU+国产OS+国产数据库\n5. AI赋能：智能审批+政务问答机器人',
    source: '网络整理',
  },
  {
    title: '如何设计医疗影像AI辅助诊断系统的技术架构？',
    content: '考察AI+医疗的交叉领域方案设计。需涵盖影像数据采集(DICOM)、AI推理服务、标注训练平台、临床工作流集成。\n延伸：如何满足NMPA(国家药监局)对AI医疗产品的审批要求？',
    category: 'industry',
    tags: [{ key: 'position', value: 'SA' }, { key: 'industry', value: '医疗' }, { key: 'company', value: '阿里云' }, { key: 'skill', value: 'AI' }],
    difficulty: 'hard',
    referenceAnswer: '1. 数据采集：DICOM标准对接PACS+脱敏处理\n2. AI推理：GPU集群+模型服务化(Triton/TF Serving)\n3. 训练平台：标注工具+AutoML+模型版本管理\n4. 临床集成：报告回写PACS/RIS+医生审核流程\n5. 合规：数据匿名化+审计日志+三类医疗器械认证',
    source: '网络整理',
  },
  {
    title: '如何为制造企业设计工业互联网平台方案？',
    content: '考察制造行业数字化转型能力。需涵盖设备联网(IoT)、数据采集、数字孪生、预测性维护、MES/ERP集成。\n延伸：如何处理OT(运营技术)和IT(信息技术)融合的挑战？',
    category: 'industry',
    tags: [{ key: 'position', value: 'SA' }, { key: 'industry', value: '制造' }, { key: 'company', value: '阿里云' }, { key: 'skill', value: '大数据' }],
    difficulty: 'hard',
    referenceAnswer: '1. 设备联网：IoT网关+协议转换(OPC UA/MQTT)\n2. 数据平台：时序数据库+流式计算+数据湖\n3. 数字孪生：3D建模+实时数据驱动+仿真\n4. 预测维护：设备健康度模型+故障预警\n5. IT/OT融合：边缘计算+DMZ隔离+统一数据模型',
    source: '网络整理',
  },
  {
    title: '如何评估客户的云成熟度并制定上云路线图？',
    content: '考察SA的方法论和咨询能力。需要有结构化的评估框架(如Gartner的5阶段模型)，以及分阶段实施路径设计能力。\n延伸：如何说服一个"不想上云"的CTO？',
    category: 'industry',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '通用' }, { key: 'skill', value: '云计算' }],
    difficulty: 'medium',
    referenceAnswer: '1. 评估维度：应用/基础设施/数据/组织/安全 5维度\n2. 成熟度等级：初始→可重复→定义→管理→优化\n3. 路线图：评估→试点→迁移→优化(6-18个月)\n4. 优先级：按6R策略(Rehost/Replatform/Refactor/Rebuild/Replace/Retire)\n5. 说服：TCO对比+标杆案例+渐进式验证',
    source: '网络整理',
  },
  {
    title: '如何设计数据中台架构以支撑企业的数字化转型？',
    content: '考察数据架构和中台设计能力。需涵盖数据采集(ETL/CDC)、数据仓库(离线+实时)、数据治理、数据服务API、数据安全。\n延伸：数据中台和业务中台的关系是什么？如何避免中台变成"中台债"？',
    category: 'architecture',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '通用' }, { key: 'skill', value: '大数据' }, { key: 'skill', value: 'AI' }],
    difficulty: 'hard',
    referenceAnswer: '1. 数据采集：CDC(Debezium)+批量(Spark/Flume)\n2. 数仓分层：ODS→DWD→DWS→ADS(MaxCompute/Flink)\n3. 数据治理：数据目录+质量规则+血缘追踪+分级脱敏\n4. 数据服务：API网关+数据沙箱+自助查询\n5. 避免中台债：小步快跑+价值驱动+先做高频场景',
    source: '网络整理',
  },

  // =========================================
  // J. 售前软技能 - 新增刷题题库 (8题)
  // =========================================
  {
    title: '客户需求不明确时，你如何引导和挖掘客户的真实需求？',
    content: '考察需求分析和引导能力。需展示结构化的需求调研方法：从业务痛点出发，通过提问引导客户自己发现需求，而非被动接受客户的功能清单。\n延伸：客户说"我要一个中台"，你如何判断他是否真的需要？',
    category: 'presales',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '通用' }],
    difficulty: 'medium',
    referenceAnswer: '1. 调研准备：行业研究+竞品分析+预设问题清单\n2. 访谈技巧：SPIN法(现状→问题→暗示→需求回报)\n3. 需求验证：原型Demo+场景模拟+ROI测算\n4. 中台判断：先问业务痛点→看系统现状→评估ROI\n5. 交付：需求规格书+优先级排序+分期规划',
    source: '网络整理',
  },
  {
    title: '如何设计一个成功的POC(概念验证)项目？从目标设定到成果汇报的全流程',
    content: '考察POC项目管理能力。需涵盖POC目标设定(与采购决策挂钩)、范围控制(小而精)、成功标准量化、时间盒管理、汇报技巧。\n延伸：POC做了很久但客户一直不决策，你怎么处理？',
    category: 'presales',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '通用' }],
    difficulty: 'medium',
    referenceAnswer: '1. 目标对齐：与客户共同定义成功标准(KPI)\n2. 范围控制：2-4周+3个核心场景\n3. 执行：每日同步+问题清单+变更控制\n4. 汇报：数据说话+对比分析+ROI测算\n5. 催决策：设定Deadline+高层互访+竞品对比',
    source: '网络整理',
  },
  {
    title: '在招投标过程中，SA如何做好技术标书和答辩？',
    content: '考察招投标实战能力。需涵盖技术标书结构设计、评分标准解读、差异化亮点提炼、答辩PPT制作、Q&A预案准备。\n延伸：如果评分标准中价格占60%，技术标怎么做才能赢？',
    category: 'presales',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '通用' }],
    difficulty: 'medium',
    referenceAnswer: '1. 标书结构：方案概述+架构设计+实施计划+案例+报价\n2. 评分策略：逐条对照评分标准响应，不遗漏\n3. 差异化：突出行业案例+产品优势+增值服务\n4. 答辩：10分钟PPT(痛点→方案→案例→ROI)+Q&A\n5. 价格劣势：技术分拉大差距+TCO长期价值',
    source: '网络整理',
  },
  {
    title: '客户对方案提出"你们和XX厂商比有什么优势"，你如何回应？',
    content: '考察竞品分析和售前应变能力。需展示不贬低对手、突出自身差异化价值的沟通策略，同时需要了解主流云厂商的差异化定位。\n延伸：如果客户明确倾向竞品，你如何扭转局面？',
    category: 'presales',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '阿里云' }],
    difficulty: 'medium',
    referenceAnswer: '1. 原则：不贬低对手+聚焦自身优势+用数据说话\n2. 阿里云优势：生态完善+技术领先(飞天)+行业深耕\n3. 策略：找到客户最关注的痛点，展示差异化能力\n4. 证据：同行业标杆案例+第三方评测报告\n5. 扭转：找到竞品方案的薄弱环节+安排深度技术交流',
    source: '网络整理',
  },
  {
    title: '如何向非技术背景的高管(CXO)汇报技术方案？',
    content: '考察方案汇报和沟通表达能力。需要将复杂技术概念转化为业务语言，聚焦ROI、风险、战略价值而非技术细节。\n延伸：汇报时高管突然问了一个你没准备的尖锐问题，怎么处理？',
    category: 'presales',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '通用' }],
    difficulty: 'medium',
    referenceAnswer: '1. 结构：痛点共鸣→方案价值→成功案例→投资回报→下一步\n2. 语言：避免技术术语，用业务语言(收入/成本/风险)\n3. 可视化：一页纸架构图+流程图+ROI图表\n4. 时间控制：15分钟内+留Q&A时间\n5. 突发问题：坦诚+承诺跟进+会后24h内回复',
    source: '网络整理',
  },
  {
    title: '如何管理客户期望，当客户提出的需求超出产品能力时？',
    content: '考察期望管理和客户沟通能力。需展示如何在不伤害客户关系的前提下管理需求边界，同时推动产品团队迭代。\n延伸：销售为了签单过度承诺功能，你作为SA如何处理？',
    category: 'presales',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '通用' }],
    difficulty: 'medium',
    referenceAnswer: '1. 倾听理解：先确认客户的业务目标(不是功能需求)\n2. 替代方案：用现有能力满足80%+定制化补齐20%\n3. 期望管理：明确说"能做/不能做/将来可能做"\n4. 路线图：将需求排入产品Backlog+给出时间预期\n5. 内部协调：与销售对齐+推动PM优先排期',
    source: '网络整理',
  },
  {
    title: '描述一个你曾处理过的项目延期或交付风险案例，你是如何处理的？',
    content: '考察项目管理和风险应对能力。建议用STAR法则展开：Situation(背景)→Task(任务)→Action(行动)→Result(结果)。\n延伸：如何建立项目风险预警机制？',
    category: 'teamwork',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '通用' }],
    difficulty: 'medium',
    referenceAnswer: '1. 风险识别：WBS分解+关键路径分析+依赖梳理\n2. 预警机制：红黄绿灯周报+里程碑检查+燃尽图\n3. 应对策略：赶工(加资源)/快速跟进(并行)/范围裁剪\n4. 沟通：提前告知客户+给出选项+让客户参与决策\n5. 复盘：根因分析+改进措施+组织知识沉淀',
    source: '网络整理',
  },
  {
    title: '如何制定一个有效的客户拜访计划和拜访后跟进策略？',
    content: '考察客户管理和商机推进能力。需涵盖拜访前准备(客户研究/目标设定)、拜访中执行(需求挖掘/方案展示)、拜访后跟进(纪要/行动项)。\n延伸：首次拜访和方案汇报的拜访策略有什么不同？',
    category: 'presales',
    tags: [{ key: 'position', value: 'SA' }, { key: 'company', value: '通用' }],
    difficulty: 'easy',
    referenceAnswer: '1. 拜访前：客户研究+行业分析+明确目标+准备材料\n2. 拜访中：破冰→需求挖掘→方案展示→约定下一步\n3. 拜访后：24h内发纪要+行动项+责任人+Deadline\n4. 首次拜访：重建立关系+了解业务+收集信息\n5. 方案汇报：重价值呈现+差异化+推动决策',
    source: '网络整理',
  },
];

export function getSeedQuestions(): Omit<Question, 'id' | 'createdAt' | 'updatedAt' | 'stats'>[] {
  return SEED_QUESTIONS;
}

export function createQuestionFromSeed(seed: Omit<Question, 'id' | 'createdAt' | 'updatedAt' | 'stats'>): Question {
  const now = new Date().toISOString();
  return {
    ...seed,
    id: generateId(),
    stats: { timesAttempted: 0, timesCorrect: 0, averageScore: 0 },
    createdAt: now,
    updatedAt: now,
  };
}
